---
- name: Install Apache
  hosts: localhost
  connection: local
  gather_facts: false
  become: true

  tasks:

  - name: Install Apache
    ansible.builtin.package:
      name: apache2
      state: present