---
- name: Reset System for Kubernetes Release Monitoring
  hosts: localhost
  connection: local
  gather_facts: false
  become: true

  vars:
    kubernetes_cli_version: "v1.22.6"

  tasks:

  - name: Uninstall Apache
    ansible.builtin.package:
      name: apache2
      state: absent

  - name: Uninstall OneAgent
    ansible.builtin.shell:
      cmd: ./uninstall.sh
    args:
      chdir: /opt/dynatrace/oneagent/agent

  - name: Install kubectl
    ansible.builtin.shell:
      cmd: "curl -LO https://dl.k8s.io/release/{{ kubernetes_cli_version }}/bin/linux/amd64/kubectl && install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl"
  
  - name: Install k3s
    ansible.builtin.shell:
      cmd: "curl -sfL https://get.k3s.io | sh -s - --disable traefik"

  - name: Create ~/.kube directory
    file:
      path: ~/.kube
      state: directory
      
  - name: Copy kubeconfig
    ansible.builtin.copy:
      remote_src: yes
      src: /etc/rancher/k3s/k3s.yaml
      dest: ~/.kube/config