---
- name: Restart Apache
  hosts: localhost
  connection: local
  gather_facts: false
  become: true

  tasks:

  - name: Restart Apache
    ansible.builtin.service:
      name: apache2
      state: restarted