---
- name: Set OneAgent Host Group
  hosts: localhost
  connection: local
  gather_facts: false
  become: true

  tasks:

  - name: Stop OneAgent
    ansible.builtin.service:
      name: oneagent
      state: stopped

  - name: Set Host Group
    ansible.builtin.shell:
      cmd: "./oneagentctl --set-host-group at-demo-release"
    args:
      chdir: /opt/dynatrace/oneagent/agent/tools

  - name: Start OneAgent
    ansible.builtin.service:
      name: oneagent
      state: started