---
- hosts: localhost
  connection: local
  gather_facts: false

  vars_prompt:

    - name: dt_tenant
      prompt: What is your DT environment (no trailing slash eg. https://abc12345.live.dynatrace.com)?
      private: false

    - name: dt_api_token
      prompt: What is your DT API Token?
      private: false

  tasks:

  - name: "Create Host Group Auto Tag Rule"
    ansible.builtin.uri:
      url: "{{ dt_tenant }}/api/config/v1/autoTags"
      method: POST
      status_code: 201
      body_format: json
      headers:
        Authorization: "Api-token {{dt_api_token}}"
      body: >-
        {
          "name": "at-host-group",
          "description": null,
          "rules": [{
            "type": "HOST",
            "enabled": true,
            "valueFormat": "{HostGroup:Name}",
            "normalization": "LEAVE_TEXT_AS_IS",
            "propagationTypes": [ "HOST_TO_PROCESS_GROUP_INSTANCE" ],
            "conditions": [{
              "key": {
                "attribute": "HOST_GROUP_NAME",
                "type": "STATIC"
               },
              "comparisonInfo": {
                  "type": "STRING",
                  "operator": "EXISTS",
                  "value": null,
                  "negate": false,
                  "caseSensitive": null
                  }
                }]
            }],
          "entitySelectorBasedRules": []
        }

  - name: "Create Process Group Auto Tag Rule"
    ansible.builtin.uri:
      url: "{{ dt_tenant }}/api/config/v1/autoTags"
      method: POST
      status_code: 201
      body_format: json
      headers:
        Authorization: "Api-token {{dt_api_token}}"
      body: >-
        {
          "name": "at-pg-tag",
          "description": null,
          "rules": [{
            "type": "PROCESS_GROUP",
            "enabled": true,
            "valueFormat": "webserver",
            "normalization": "LEAVE_TEXT_AS_IS",
            "propagationTypes": [],
            "conditions": [{
              "key": {
                "attribute": "PROCESS_GROUP_DETECTED_NAME",
                "type": "STATIC"
              },
                "comparisonInfo": {
                    "type": "STRING",
                    "operator": "CONTAINS",
                    "value": "apache",
                    "negate": false,
                    "caseSensitive": true
                    }
                  }]
            }],
            "entitySelectorBasedRules": []
        }