---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:

  - name: "Running Release (Press Ctrl + C to end when you see a problem in Dynatrace)"
    ansible.builtin.shell:
      cmd: "stress -c 1 -t 5m"